# Generated by Django 5.0.1 on 2024-01-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdur', models.IntegerField()),
                ('ccat', models.CharField(max_length=50)),
                ('cprice', models.IntegerField()),
            ],
        ),
    ]
